#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"
ENV_FILE="$DEPLOY_DIR/.env"
BUNDLE_FILE="$DEPLOY_DIR/images/xiaosongshu-images.tar"
VERIFY=true

if [[ ! -f "$ENV_FILE" ]]; then
	ENV_FILE="$DEPLOY_DIR/.env.example"
fi

usage() {
	cat <<EOF
Usage: $0 [options]

Load the offline image bundle generated by deploy/scripts/pack-images.sh.

Options:
  -i, --input <file>       Bundle tar path. Default: deploy/images/xiaosongshu-images.tar
  --compose-file <file>    Compose file path. Default: deploy/docker-compose.yml
  --env-file <file>        Compose env file path. Default: deploy/.env or deploy/.env.example
  --no-verify             Skip verifying compose images after load.
  -h, --help              Show this help.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		--)
			shift
			;;
		-i|--input)
			BUNDLE_FILE="$2"
			shift 2
			;;
		--compose-file)
			COMPOSE_FILE="$2"
			shift 2
			;;
		--env-file)
			ENV_FILE="$2"
			shift 2
			;;
		--no-verify)
			VERIFY=false
			shift
			;;
		-h|--help)
			usage
			exit 0
			;;
		*)
			echo "Unknown argument: $1" >&2
			usage >&2
			exit 1
			;;
	esac
done

if [[ ! -f "$BUNDLE_FILE" ]]; then
	echo "Bundle file not found: $BUNDLE_FILE" >&2
	exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
	rm -rf "$tmp_dir"
}
trap cleanup EXIT

tar -C "$tmp_dir" -xf "$BUNDLE_FILE"

manifest_file="$tmp_dir/manifest.tsv"
if [[ ! -f "$manifest_file" ]]; then
	echo "Bundle manifest not found: manifest.tsv" >&2
	exit 1
fi

inspect_image() {
	docker image inspect "$1" >/dev/null 2>&1
}

load_image_tar_as() {
	local image="$1"
	local tar_file="$2"
	local load_output=''
	local loaded_ref=''
	local loaded_id=''

	echo "Loading $tar_file -> $image"
	load_output="$(docker load -i "$tar_file")"
	printf '%s\n' "$load_output"

	if inspect_image "$image"; then
		return 0
	fi

	loaded_ref="$(printf '%s\n' "$load_output" | sed -n 's/^Loaded image: //p' | tail -n 1)"
	loaded_id="$(printf '%s\n' "$load_output" | sed -n 's/^Loaded image ID: //p' | tail -n 1)"

	if [[ -n "$loaded_ref" ]]; then
		docker tag "$loaded_ref" "$image"
	elif [[ -n "$loaded_id" ]]; then
		docker tag "$loaded_id" "$image"
	fi

	if ! inspect_image "$image"; then
		echo "Failed to tag loaded image as: $image" >&2
		exit 1
	fi
}

while IFS=$'\t' read -r image relative_tar; do
	if [[ -z "$image" || -z "$relative_tar" ]]; then
		continue
	fi

	tar_file="$tmp_dir/$relative_tar"
	if [[ ! -f "$tar_file" ]]; then
		echo "Image tar listed in manifest does not exist: $relative_tar" >&2
		exit 1
	fi

	load_image_tar_as "$image" "$tar_file"
done < "$manifest_file"

if [[ "$VERIFY" != true ]]; then
	echo "Loaded bundle: $BUNDLE_FILE"
	exit 0
fi

if [[ ! -f "$COMPOSE_FILE" ]]; then
	echo "Compose file not found: $COMPOSE_FILE" >&2
	exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
	echo "Env file not found: $ENV_FILE" >&2
	exit 1
fi

mapfile -t IMAGES < <(
	docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" config --images \
		| sed '/^[[:space:]]*$/d' \
		| sort -u
)

missing=()
for image in "${IMAGES[@]}"; do
	if ! inspect_image "$image"; then
		missing+=("$image")
	fi
done

if [[ "${#missing[@]}" -gt 0 ]]; then
	echo "Loaded bundle, but these compose images are still missing:" >&2
	printf '  %s\n' "${missing[@]}" >&2
	exit 1
fi

echo "Loaded and verified compose images:"
printf '  %s\n' "${IMAGES[@]}"
